language: java
jdk:
- oraclejdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: mDOdojpzJ7bUf3evGON3Wjtc7OhM5dHiIZDzXXA1p68lPsONIVVKu3aMbHDaOGMP0tVg93+uKjSCU9CBo+G2L5tEk7CHHQuv59aBXksQT+SiN0bWcxuEFCGiCFhsBf/GQ/jLAk/vUpGjjfQG2SFxu2No9sRPeH4uxnRWFtmzvssyTYpdctYAVptJnZP04j/HLMcAuUS1lJpfB72J0LINI94G2LngTr3yegN6wGqAAoEGqLE6mx7X8CzTvkp0ZMnkj8gWYwRgZitfKv6f0yrzzq41uwuDV9Qq4AuE9sAQ1mHwEPgko5mGeBQIezCTUWyCUI+Dh7iD3l5KTJ5nb2AxHBPPrEZVryn8wfSvuQmRWqv1QyvI2xS8BS/uB1mDWtfsLdqh0ydn1O3JGOKEGYZATGZayxG+69byX37JKvor80WwdOkDN/o8thahvdseffpx/4Zzg0m2Vrj1GEUI1WYk2NW49WwmB3vsSCTkL64U8PYjFvBVzyCK6RWSIZSgsIfiwPTyGE/kLaybQkkW6WCuXx1CxLE8VNOxU4LUhHI8w+KgQyFmBwLhEiKs6N7abW5/cbF3DwtEYQd6lJBHIDt3p0uN4YyzHhyrz/v0UcBYnyGA2F41LFONfX2l03XyPasiRESBdVHPOrh2ZTjItrag5Xhy42xIQmcZux0yiz8h5oc=
  app: basic-web-app-db